name: Test

on: pull_request

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      env:
        FAUNA_DB: ${{ secrets.FAUNA_DB }}
      - run: npm ci
      - run: npm run install:all
      - run: npm run test
